version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ../.env
    depends_on:
      - db
      - migration
      - redis

  migration:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: poetry run python3 manage.py migrate
    depends_on:
      - db
    env_file:
      - ../.env

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - ${REDIS_PORT}

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    env_file:
      - ../.env

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A config worker -l info
    depends_on:
      - web
    env_file:
      - ../.env

  flower:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A config.celery:app flower
    depends_on:
      - web
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    env_file:
      - ../.env

volumes:
  postgres_data:
